/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddSocket: typeof import('./components/AddSocket.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Canvas: typeof import('./components/Canvas.vue')['default']
    ColorMenu: typeof import('./components/ColorMenu.vue')['default']
    Connection: typeof import('./components/Connection.vue')['default']
    Connections: typeof import('./components/Connections.vue')['default']
    ConnectionTemp: typeof import('./components/ConnectionTemp.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputOutput: typeof import('./components/InputOutput.vue')['default']
    Inputs: typeof import('./components/Inputs.vue')['default']
    LabelMenu: typeof import('./components/LabelMenu.vue')['default']
    Layer: typeof import('./components/Layer.vue')['default']
    Node: typeof import('./components/Node.vue')['default']
    NodeOptions: typeof import('./components/NodeOptions.vue')['default']
    Nodes: typeof import('./components/Nodes.vue')['default']
    OptionsMenu: typeof import('./components/OptionsMenu.vue')['default']
    Outputs: typeof import('./components/Outputs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Socket: typeof import('./components/Socket.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
  }
}
